### ISSUE TITLE
Bug création ligues by admin

### ISSUE THREAD

**Issue by wezerg** [lGabranth/M2L_note_de_frais#1]
Bonjour, dans le module administrateur de gestion des ligues il semble il y avoir une anomalie. 

Lorsque l'on créer une nouvelle ligue et que l'on y affecte un directeur déjà affecté dans une autre ligue, ce dernier récupère 2 ligues.

![incident_ligue_directeur](https://user-images.githubusercontent.com/55143351/72801876-c5ae4380-3c4a-11ea-8966-3dfc2bc82d31.png)

Hors une ligue ne peux posséder qu'un seul directeur.

Merci d'avance pour le rectificatif.

**Comment by lGabranth** [comment]
Bonjour, 
Il y avait un bug sur la modification qui, en effet, n'enlevait pas le nouveau directeur de son rôle en ancienne ligue. Problème patché !

Si jamais votre problème en ajout persiste, merci de bien vouloir me contacter car je n'ai pas réussi à reproduire le bug.

Cordialement.
